---
name: 'Terraform'

on:
  push:
    branches:
      - master
    paths:
      - 'terraform-main/**'
  pull_request:
    branches:
      - master
    paths:
      - 'terraform-main/**'
  workflow_dispatch:
    inputs:
      apply:
        description: 'check this to apply changes'
        required: false
        type: boolean
        default: 'false'
      destroy:
        description: 'check this to destroy infrastructure'
        required: false
        type: boolean
        default: 'false'

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    env:
      TOKEN: ${{ secrets.YC_TOKEN }}
      CLOUD_ID: ${{ secrets.YC_CLOUD_ID }}
      FOLDER_ID: ${{ secrets.YC_FOLDER_ID }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: "1.14.0"

    - name: Terraform Init
      run: terraform -chdir=./terraform-main init

    - name: Terraform Format and Validate
      run: terraform -chdir=./terraform-main validate

    - name: Terraform Plan
      run: |
        terraform -chdir=./terraform-main plan -input=false -out=tfplan \
        -var="token=${{ secrets.YC_TOKEN }}" \
        -var="cloud_id=${{ secrets.YC_CLOUD_ID }}" \
        -var="folder_id=${{ secrets.YC_FOLDER_ID }}"

    - name: Terraform Apply (Automatic)
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: terraform -chdir=./terraform-main apply -input=false tfplan

    - name: Terraform Apply (Manual)
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.apply == 'true'
      run: terraform -chdir=./terraform-main apply -input=false tfplan

    - name: Terraform Destroy (Manual)
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.destroy == 'true'
      run: |
        terraform -chdir=./terraform-main destroy -input=false -auto-approve \
        -var="token=${{ secrets.YC_TOKEN }}" \
        -var="cloud_id=${{ secrets.YC_CLOUD_ID }}" \
        -var="folder_id=${{ secrets.YC_FOLDER_ID }}"
